# Generated by Django 5.2.6 on 2025-11-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('placa', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=25)),
                ('kilometraje', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('precio', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
